export const GET_ACCOUNT_DATA = 'GET_ACCOUNT_DATA';
export const FAIL_GET_ACCOUNT_DATA = 'FAIL_GET_ACCOUNT_DATA';
export const DELETE_ACCOUNT_DATA = 'DELETE_ACCOUNT_DATA';
export const FAIL_DELETE_ACCOUNT_DATA = 'FAIL_DELETE_ACCOUNT_DATA';